config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#index'

  resources :rooms, only: [:index, :create, :show], param: :title
  resources :messages, only: :create

  namespace :api do
    namespace :v1 do
      resources :rooms, only: :index
      resources :messages, only: :create
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :body, presence: true

  scope :sorted, -> { order(:id) }
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages, -> { sorted }, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rooms, dependent: :destroy
  has_many :messages
end

app/controllers/api/v1/base_controller.rb
module Api
  module V1
    class BaseController < ApplicationController
      protect_from_forgery with: :null_session

      def set_guest_user!
        @guest_user ||= User.find_by!(email: 'guest@example.com')
      end

      private

      def render_not_found
        render json: { errors: ['Запись не найдена'] }, status: :not_found
      end
    end
  end
end

app/controllers/api/v1/messages_controller.rb
module Api
  module V1
    class MessagesController < BaseController
      before_action :set_guest_user!, only: :create
      before_action :find_room!, only: :create

      def create
        @new_message = @guest_user.messages.create!(message_params)

        room = @new_message.room
        @new_message.broadcast_append_to room, target: "room_#{room.id}_messages", locals: { message: @new_message }

        render json: @new_message, status: :ok
      end

      private

      def message_params
        params.require(:message).permit(:body, :room_id)
      end

      def find_room!
        @room = Room.find_by!(id: message_params[:room_id])
      end
    end
  end
end

app/controllers/api/v1/rooms_controller.rb
module Api
  module V1
    class RoomsController < BaseController
      def index
        @rooms = Room.all
        render json: @rooms, status: :ok
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::NotNullViolation, with: :render_invalid_error
  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found

  private

  def set_current_user
    @current_user = current_user
    redirect_to new_user_session_path unless @current_user
  end

  def render_invalid_error
    flash[:error] = 'Не заполнены необходимые поля'
    redirect_to root_path
  end

  def render_not_found
    flash[:error] = 'Запись не найдена'
    redirect_to root_path
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @new_message = current_user.messages.create!(message_params)

    room = @new_message.room
    @new_message.broadcast_append_to room, target: "room_#{room.id}_messages", locals: { message: @new_message }
  end

  private

  def message_params
    params.require(:message).permit(:body, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_current_user, only: [:index, :show]

  def index
    @rooms = Room.all
    @new_room = Room.new
  end

  def show
    @room = Room.find_by!(title: params[:title])
    @messages = @room.messages
    @new_message = current_user.messages.build
  end

  def create
    @new_room = current_user.rooms.create!(title: room_params[:title])
    @new_room.broadcast_append_to :rooms
  end

  private

  def room_params
    params.require(:room).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/flash' %>

    <div class="min-h-full">
      <nav class="bg-gray-800">
        <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div class="flex h-16 items-center justify-between">
            <div class="flex items-center">
              <div class="flex-shrink-0">
                <a href="/">
                  <img class="h-8 w-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
                </a>
              </div>
              <div class="hidden md:block">
                <div class="ml-10 flex items-baseline space-x-4">
                  <% if user_signed_in? %>
                    <div class= "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">
                      <%= current_user.email%>
                    </div>
                    <%= link_to "Sign out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"%>
                  <% else %>
                    <%= link_to "Sign in", new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"%>
                    <%= link_to "Sign up", new_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"%>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Mobile menu, show/hide based on menu state. -->
        <div class="md:hidden" id="mobile-menu">
          <div class="space-y-1 px-2 pb-3 pt-2 sm:px-3">
            <% if user_signed_in? %>
              <%= link_to "Sign out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium"%>
            <% else %>
              <%= link_to "Sign in", new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium"%>
              <%= link_to "Sign up", new_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium"%>
            <% end %>
          </div>
        </div>
      </nav>

      <header class="bg-white shadow">
        <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
          <h1 class="text-3xl font-bold tracking-tight text-gray-900">Online chat</h1>
        </div>
      </header>
      <main>
        <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
          <%= yield %>
        </div>
      </main>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg my-4 py-2 pl-1">
  <div class="flex flex-row">
    <div class="basis-3/12"><%= message.user.email %></div>
    <div class="basis-7/12">
      <%= message.body %>
      <div class="basis-1/12"><%= l(message.created_at, format: :short) %></div>
    </div>
  </div>
</div>

app/views/rooms/_room.html.erb
<div> <%= link_to room.title, room_path(room.title) %> </div>

app/views/rooms/index.html.erb
<%= turbo_stream_from :rooms %>

<div>
  <%= render @rooms %>
</div>

<%= form_with url: rooms_path, scope: :room, method: :post do |f| %>
  <%= f.text_field :title, class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>
  <%= f.submit 'Создать комнату', class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 cursor-pointer" %>
<% end %>

app/views/rooms/show.html.erb
<%= turbo_stream_from @room %>

<div class="flex flex-col h-96 justify-between">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8" id="chat-container">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8" id="room_<%= @room.id %>_messages">
      <%= render partial: "messages/message", collection: @messages %>
    </div>
  </div>
</div>

<%= form_with model: @new_message do |f| %>
  <div class="rounded-md shadow-sm -space-y-px">
    <%= f.text_field :body, autofocus: true, required: true, placeholder: "Your text", class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>
    <%= f.hidden_field :room_id, value: @room.id %>
<% end %>

app/views/shared/_flash.html.erb
<div class="flash-messages">
  <% flash.each do |type, message| %>
    <div class="flash-message">
      <%= message %>
    </div>
  <% end %>
</div>